import 'package:flutter/material.dart';
import '../../../../app/theme/app_colors.dart';
import '../../../../core/localization/app_localizations.dart';
import '../../../../core/utils/date_time_utils.dart';
import '../../../../models/dose_instance.dart';

class DoseCard extends StatelessWidget{final DoseInstance dose;final VoidCallback? onConfirm,onSnooze,onSkip,onTap;final bool compact;const DoseCard({super.key,required this.dose,this.onConfirm,this.onSnooze,this.onSkip,this.onTap,this.compact=false});
 @override Widget build(BuildContext context){final l=AppLocalizations.of(context);final theme=Theme.of(context);final statusColor=AppColors.statusColor(_dbStatus);final actionable=dose.status==DoseStatus.pending||dose.status==DoseStatus.reminderSent||dose.status==DoseStatus.snoozed;final card=Card(child:Padding(padding:EdgeInsets.all(compact?14:18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Container(width:44,height:44,decoration:BoxDecoration(color:statusColor.withValues(alpha:.14),borderRadius:BorderRadius.circular(12)),child:Icon(Icons.medication_liquid_rounded,color:statusColor)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(dose.medicationName,style:theme.textTheme.titleMedium?.copyWith(fontWeight:FontWeight.w700)),Text('${dose.doseAmount} — ${DateTimeUtils.formatTime(dose.scheduledAt)}',style:theme.textTheme.bodySmall)])),_StatusChip(status:dose.status)]),if(actionable&&!compact)...[const SizedBox(height:14),Row(children:[Expanded(flex:2,child:ElevatedButton.icon(onPressed:onConfirm,icon:const Icon(Icons.check_circle_rounded,size:20),label:Text(_tr(context,'أخذت الدواء','I took it','J’ai pris le médicament'))),),const SizedBox(width:8),Expanded(child:OutlinedButton(onPressed:onSnooze,child:Text(_tr(context,'لاحقًا','Later','Plus tard'))))]),TextButton(onPressed:onSkip,child:Text(l.skip))]])));if(onTap==null)return card;return Semantics(button:true,label:_tr(context,'فتح ${dose.medicationName}','Open ${dose.medicationName}','Ouvrir ${dose.medicationName}'),child:InkWell(borderRadius:BorderRadius.circular(12),onTap:onTap,child:card));}
 String get _dbStatus=>switch(dose.status){DoseStatus.pending=>'PENDING',DoseStatus.reminderSent=>'REMINDER_SENT',DoseStatus.snoozed=>'SNOOZED',DoseStatus.taken=>'TAKEN',DoseStatus.missed=>'MISSED',DoseStatus.skipped=>'SKIPPED',DoseStatus.cancelled=>'CANCELLED'};
}
String _tr(BuildContext c,String ar,String en,String fr)=>switch(AppLocalizations.of(c).locale.languageCode){'en'=>en,'fr'=>fr,_=>ar};
class _StatusChip extends StatelessWidget{final DoseStatus status;const _StatusChip({required this.status});@override Widget build(BuildContext context){final l=AppLocalizations.of(context);final color=switch(status){DoseStatus.taken=>AppColors.success,DoseStatus.missed=>AppColors.danger,DoseStatus.snoozed=>AppColors.warning,DoseStatus.reminderSent=>AppColors.warning,DoseStatus.skipped=>AppColors.neutral,DoseStatus.cancelled=>AppColors.neutral,DoseStatus.pending=>AppColors.primary};return Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:5),decoration:BoxDecoration(color:color.withValues(alpha:.14),borderRadius:BorderRadius.circular(20)),child:Text(l.doseStatus(switch(status){DoseStatus.taken=>'TAKEN',DoseStatus.missed=>'MISSED',DoseStatus.snoozed=>'SNOOZED',DoseStatus.reminderSent=>'REMINDER_SENT',DoseStatus.skipped=>'SKIPPED',DoseStatus.cancelled=>'CANCELLED',DoseStatus.pending=>'PENDING'}),style:TextStyle(color:color,fontSize:12,fontWeight:FontWeight.w700)));}}
